### PR TITLE
feat: Add meta info to plugin

### PR DESCRIPTION
**Pull request by nzakas**
#### Prerequisites checklist

-   [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request?

Add meta info to the plugin

#### What changes did you make? (Give an overview)

- added `meta` object to the plugin
- updated `release-please-config.json` to update `src/index.js` with the correct version number
- removed `release-as` from `release-please-config.json`

### CODE REVIEW

**Comment by nzakas** [comment]
Not sure what the problem is with Node.js v22. Hopefully just a transient.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks! Just waiting for CI to be fixed. Hopefully a patch in Node.js 22.5 will be released soon, otherwise we might want to pin 22.4.

**Comment by mdjermanovic** [comment]
Just one more thing - this looks like something we'd want to release, so perhaps it should be tagged as `feat`?

**Comment by nzakas** [comment]
Good call. :+1:

**Pull request merged**
