### PR TITLE
chore: Post release announcements across services

### PR DESCRIPTION
**Pull request by nzakas**
#### Prerequisites checklist

-   [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request?

Update how we post release announcements. This will now post to Twitter, Mastodon, and Bluesky.

#### What changes did you make? (Give an overview)

- Switched to use `@humanwhocodes/crosspost` to post across multiple services in one step
- Added organization secrets and variables for the BlueSky info

#### Is there anything you'd like reviewers to focus on?

I've tested this on my own project and it worked, but want to just try this out on one of our repos to verify that everything is configured correctly before rolling out across the org.

### CODE REVIEW

**Comment by nzakas** [comment]
I don't understand why there's a Prettier error. When I check locally everything is fine. :thinking:

**Comment by fasttime** [comment]
Prettier v3.4 was published today and it expects Markdown list items to contain only one space after the leading `-`: https://prettier.io/blog/2024/11/26/3.4.0#markdown.

**Comment by fasttime** [comment]
> I don't understand why there's a Prettier error. When I check locally everything is fine. 🤔

@nzakas I can see the errors after deleting and reinstalling `node_modules`. Maybe we should update the prettier dependency to `"^3.4.1"` in `package.json` to make sure everybody has the latest version. If we don't want to have to change the formatting after a minor Prettier release, we could also pin the minor version with `"~3.4.1"`.

**Comment by nzakas** [comment]
Ah thanks. That's annoying. I've updated the PR.

**Review by fasttime — APPROVED** [review]
LGTM, thanks! It's fine to test the new announcements tool on this repo first.

**Pull request merged**
